package it.gesp.geoportal.constants;

public interface GeneralSettings {

	/*
	 * INITIAL MESSAGE
	 */
	String INITIAL_MESSAGE = "INITIAL_MESSAGE";
	
	/*
	 * SHOW INITIAL MESSAGE
	 */
	String SHOW_INITIAL_MESSAGE = "SHOW_INITIAL_MESSAGE";
	
	/*
	 * INFORMATION MESSAGE
	 */
	String INFORMATION_MESSAGE = "INFORMATION_MESSAGE";
	
	/*
	 * SHOW INFORMATION MESSAGE
	 */
	String SHOW_INFORMATION_MESSAGE = "SHOW_INFORMATION_MESSAGE";
}
