package it.gesp.geoportal.constants;

public interface SystemSettings {

	/*
	 * PROXY URL
	 */
	String PROXY_URL = "PROXY_URL";
	
	/*
	 * GEOSERVER URL
	 */
	String GEOSERVER_URL = "GEOSERVER_URL";
	
	/*
	 * GEONETWORK_URL
	 */
	String GEONETWORK_URL = "GEONETWORK_URL";
	
	/*
	 * PRINT_SERVLET_URL
	 */
	String PRINT_SERVLET_URL = "PRINT_SERVLET_URL";
	
	/*
	 * PRINT_IMAGES_FOLDER
	 */
	String PRINT_IMAGES_FOLDER = "PRINT_IMAGES_FOLDER";
	
	/*
	 * SEARCH_MAX_HITS_PER_LAYER
	 */
	String SEARCH_MAX_HITS_PER_LAYER = "SEARCH_MAX_HITS_PER_LAYER";
	
	/*
	 * MAX_NUMBER_OF_SELECTABLE_LAYERS
	 */
	String MAX_NUMBER_OF_SELECTABLE_LAYERS = "MAX_NUMBER_OF_SELECTABLE_LAYERS";
	/*
	 * AJAX REQUEST TIMEOUT (MSEC)
	 */
	String AJAX_REQUEST_TIMEOUT_MSEC = "AJAX_REQUEST_TIMEOUT_MSEC";
	String AJAX_REQUEST_PRINT_TIMEOUT_MSEC = "AJAX_REQUEST_PRINT_TIMEOUT_MSEC";
	
	/*
	 * FEATURE_ATTRIBUTE_HYPERLINK_FIELD
	 */
	String FEATURE_ATTRIBUTE_HYPERLINK_FIELD = "FEATURE_ATTRIBUTE_HYPERLINK_FIELD";
	
	/*
	 * ALERTS_LEGEND_URL
	 */
	String ALERTS_LEGEND_URL = "ALERTS_LEGEND_URL";
	
	/*
	 * REDLINES_LEGEND_URL
	 */
	String REDLINES_LEGEND_URL = "REDLINES_LEGEND_URL";
	
	/*
	 * ALERTS_GEOSERVER_LAYER_NAME
	 */
	String ALERTS_GEOSERVER_LAYER_NAME = "ALERTS_GEOSERVER_LAYER_NAME";
	
	/*
	 * ALERTS_GEOSERVER_USERNAME
	 */
	String ALERTS_GEOSERVER_USERNAME = "ALERTS_GEOSERVER_USERNAME";
	
	/*
	 * ALERTS_GEOSERVER_PASSWORD
	 */
	String ALERTS_GEOSERVER_PASSWORD = "ALERTS_GEOSERVER_PASSWORD";
	
}
